# Generated by Django 5.1.6 on 2025-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_backlogitem_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
