# Generated by Django 5.1.6 on 2025-12-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='paused_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
